### ISSUE TITLE
Same Config - Ends with Reboot or stuck loading the macOS installer

### ISSUE THREAD

**Issue by DerPicknicker** [Lorys89/ASROCK_Z490M-ITX-AC#2] opened 2021-05-05 06:34 UTC
Hello, 

thank you for sharing your EFI Folder an all your KEXT-Files.. Sadly I cannot boot into the macOS installer.. I have the exact same Configuration (Asrock Mainboard, i5-10600k) but I don’t have any graphics card and I wan to use the integrated Graphics from the CPU.. I try to load your BIOS-Profile but my BIOS won’t load your settings. Which Bios version do you use? 

The boot Process ends with lilu user @ disabling user patcher on request or ends with: AppleSMC running fast over the Display and ends with an reboot.. 

Thank you for your Time

**Comment by Lorys89** [comment] 2021-05-05 08:15
bios vers 1.30, configure the bios as explained at the end of my repo, the bios profile and by the same identical configuration.

**Comment by DerPicknicker** [comment] 2021-05-05 08:56
![61ED3A57-E91D-4FB3-A8F6-C75ACC4D5102](https://user-images.githubusercontent.com/64746593/117117636-112d2800-ad90-11eb-8c7e-d9015ed2dc2d.jpeg)

I uploaded a picture.. I updated my bios and load your profile. Checked the settings and boot into openCore, select the macOS Big Sur installer and then nothing happens after this message. I don’t want to use clover and I see that you get airdrop working and that’s why I wanted to use your config.. 
With Clover is was much easier to boot into the installer..

**Comment by Lorys89** [comment] 2021-05-05 09:11
I mount a wifi card dw1820a broadcom, I took off the original intel 3168. today i load the efi with updated opencore and kext a vers 0.6.9

**Comment by DerPicknicker** [comment] 2021-05-05 09:22
Okay, I will try it. Should I remove the WiFi card and try it again could a wifi-Card cause that issue?

**Comment by Lorys89** [comment] 2021-05-05 09:44
no, write your hardware and I'll give you a suitable efi

**Comment by DerPicknicker** [comment] 2021-05-05 09:53
Mainboard : z490m-itx-ac
CPU: i5 10600k 
Ssd : Simple Sata 
Graphicscard : iGpu from the CPU
RAM : https://www.amazon.de/PNY-3200MHz-Desktop-MD16GD4320016XRGB-Schwarz/dp/B08B8YMQ29

Do you need more information? 

Wifi / Bluetooth is the Stock Intel Card, later I will replace it.

**Comment by Lorys89** [comment] 2021-05-06 08:14
@DerPicknicker Test this EFI , if not work, the problem is your ssd/nvme
[EFI.zip](https://github.com/Lorys89/ASROCK_Z490M-ITX-AC/files/6432922/EFI.zip)

**Comment by DerPicknicker** [comment] 2021-05-06 09:04
I will test it later, could you explain what you changed in the EFI-Folder?

**Comment by Lorys89** [comment] 2021-05-06 09:21
this efi is for your hw , wifi intel

**Comment by DerPicknicker** [comment] 2021-05-06 12:59
But you’re using clover is that (for me) as an user a big difference or should i don’t care about it?

**Comment by Lorys89** [comment] 2021-05-06 13:27
is opencore

**Comment by Lorys89** [comment] 2021-05-06 13:55
work this efi?

**Comment by DerPicknicker** [comment] 2021-05-06 14:16
I will test it later I unzipped only That folder and saw the clover log ;)

**Comment by DerPicknicker** [comment] 2021-05-06 19:40
So good and Bad News: 
Installation works and I ended up with the setup-Part .. Account name etc.. But not all usb devices are working .. my cordless mouse don’t work but on my MacBook the same mouse works fine. Also my keyboard isn’t working (PS2) any ideas? Wifi-Card works and Bluetooth too but airdrop not. 

Any ideas?

**Comment by Lorys89** [comment] 2021-05-06 20:20
intel wifi card does not support airdrop, it changes with a native broadcom. usb port mapping is mine because it can't exceed 15 ports, create your own bespoke! you have installed the efi fine, I proceed to close the issue. read the guides on dortania for the other fixes. 
Kind regards.

**Closed** 2021-05-06 20:21 UTC

**Comment by Lorys89** [comment] 2021-05-07 08:25
<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,GfxYTile</key>
				<data>AQAAAA==</data>
				<key>AAPL,ig-platform-id</key>
				<data>BwCbPg==</data>
				<key>device-id</key>
				<data>mz4AAA==</data>
				<key>enable-hdmi20</key>
				<data>AQAAAA==</data>
				<key>force-online</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-busid</key>
				<data>AgAAAA==</data>
				<key>framebuffer-con1-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-type</key>
				<data>AAgAAA==</data>
				<key>framebuffer-con2-busid</key>
				<data>BAAAAA==</data>
				<key>framebuffer-con2-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-type</key>
				<data>AAgAAA==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>hda-gfx</key>
				<string>onboard-1</string>
				<key>igfxfw</key>
				<data>AgAAAA==</data>
				<key>model</key>
				<string>Intel UHD Graphics</string>
			</dict>
